# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "express"
        versions: ["4.x"]
      - dependency-name: "lodash"
        versions: ["^4.17.15"]
    labels:
      - "dependencies"
      - "bot"
    reviewers:
      - "santhoshtoolkit"
    assignees:
      - "santhoshtoolkit"

